version: '3'

services:
  etcd:
    image: elcolio/etcd:latest
    networks:
      - etcdnet
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
      - "7001:7001"
    volumes:
      - /data/backup/dir:/data
    environment:
      discovery: https://discovery.etcd.io/425ef6dec81e2b26146704c09c51ab22
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    depends_on:
      - etcd
    image: perconalab/percona-xtradb-cluster:5.6
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - front
      - etcdnet
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      DISCOVERY_SERVICE: etcd:2379
      XTRABACKUP_PASSWORD: mypassword
      CLUSTER_NAME: galera
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - front
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
    db_data:

networks:
     front:
     etcdnet:
